require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CrimesController do

  # This should return the minimal set of attributes required to create a valid
  # Crime. As you add validations to Crime, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all crimes as @crimes" do
      crime = Crime.create! valid_attributes
      get :index
      assigns(:crimes).should eq([crime])
    end
  end

  describe "GET show" do
    it "assigns the requested crime as @crime" do
      crime = Crime.create! valid_attributes
      get :show, :id => crime.id.to_s
      assigns(:crime).should eq(crime)
    end
  end

  describe "GET new" do
    it "assigns a new crime as @crime" do
      get :new
      assigns(:crime).should be_a_new(Crime)
    end
  end

  describe "GET edit" do
    it "assigns the requested crime as @crime" do
      crime = Crime.create! valid_attributes
      get :edit, :id => crime.id.to_s
      assigns(:crime).should eq(crime)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Crime" do
        expect {
          post :create, :crime => valid_attributes
        }.to change(Crime, :count).by(1)
      end

      it "assigns a newly created crime as @crime" do
        post :create, :crime => valid_attributes
        assigns(:crime).should be_a(Crime)
        assigns(:crime).should be_persisted
      end

      it "redirects to the created crime" do
        post :create, :crime => valid_attributes
        response.should redirect_to(Crime.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved crime as @crime" do
        # Trigger the behavior that occurs when invalid params are submitted
        Crime.any_instance.stub(:save).and_return(false)
        post :create, :crime => {}
        assigns(:crime).should be_a_new(Crime)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Crime.any_instance.stub(:save).and_return(false)
        post :create, :crime => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested crime" do
        crime = Crime.create! valid_attributes
        # Assuming there are no other crimes in the database, this
        # specifies that the Crime created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Crime.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => crime.id, :crime => {'these' => 'params'}
      end

      it "assigns the requested crime as @crime" do
        crime = Crime.create! valid_attributes
        put :update, :id => crime.id, :crime => valid_attributes
        assigns(:crime).should eq(crime)
      end

      it "redirects to the crime" do
        crime = Crime.create! valid_attributes
        put :update, :id => crime.id, :crime => valid_attributes
        response.should redirect_to(crime)
      end
    end

    describe "with invalid params" do
      it "assigns the crime as @crime" do
        crime = Crime.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Crime.any_instance.stub(:save).and_return(false)
        put :update, :id => crime.id.to_s, :crime => {}
        assigns(:crime).should eq(crime)
      end

      it "re-renders the 'edit' template" do
        crime = Crime.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Crime.any_instance.stub(:save).and_return(false)
        put :update, :id => crime.id.to_s, :crime => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested crime" do
      crime = Crime.create! valid_attributes
      expect {
        delete :destroy, :id => crime.id.to_s
      }.to change(Crime, :count).by(-1)
    end

    it "redirects to the crimes list" do
      crime = Crime.create! valid_attributes
      delete :destroy, :id => crime.id.to_s
      response.should redirect_to(crimes_url)
    end
  end

end
